name: CI/CD Pipeline

permissions:
  contents: read
  packages: write

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/405found404/app:${{ github.ref_name }} ./backend

      - name: Push Docker image
        run: docker push ghcr.io/405found404/app:${{ github.ref_name }}

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/staging'

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to staging (SSM)
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID_STAGING }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands='[
              "docker pull ghcr.io/405found404/app:staging",
              "docker stop app || true",
              "docker rm app || true",
              "docker run -d -p 80:3000 --name app ghcr.io/405found404/app:staging"
            ]'

  deploy-production:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    environment:
      name: production # manual approval

    steps:
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to production (SSM)
        run: |
          aws ssm send-command \
            --instance-ids ${{ secrets.INSTANCE_ID_PROD }} \
            --document-name "AWS-RunShellScript" \
            --parameters commands='[
              "docker pull ghcr.io/405found404/app:main",
              "docker stop app || true",
              "docker rm app || true",
              "docker run -d -p 80:3000 --name app ghcr.io/405found404/app:main"
            ]'
